Update project.yml

diff --git a/.github/workflows/project.yml b/.github/workflows/project.yml
--- a/.github/workflows/project.yml
+++ b/.github/workflows/project.yml
@@ -3,10 +3,9 @@ name: Java CI/CD Pipeline to Tomcat
 on:
   push:
     branches: [ main ]   # Trigger on push to main branch
-
-jobs:
+    jobs:
   build:
-    runs-on: ubuntu-latest
+    runs-on: [self-hosted, linux]
 
     steps:
       # 1. Checkout code
@@ -20,7 +19,17 @@ jobs:
           distribution: 'temurin'
           java-version: '17'
 
-      # 3. Build with Maven
+      # 3. Install Maven if missing
+      - name: Ensure Maven is installed
+        run: |
+          if ! command -v mvn &> /dev/null; then
+            echo "Maven not found. Installing..."
+            sudo dnf install -y maven
+          else
+            echo "Maven is already installed"
+          fi
+          mvn -version
+          # 3. Build with Maven
       - name: Build with Maven
         run: mvn clean package -DskipTests
 
@@ -30,9 +39,8 @@ jobs:
         with:
           name: myapp
           path: target/*.war
-
-  deploy:
-    runs-on: ubuntu-latest
+deploy:
+    runs-on: [self-hosted, linux]
     needs: build
     environment: production
 
